version: 2

sphinx:
   builder: html
   configuration: docs/conf.py

build:
  image: testing

python:
  version: 3.9
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
