language: python
env:
  - PIPENV_VERBOSITY=-1
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - black -v --check .
  - pytest
