language: python
env:
  - PIPENV_IGNORE_VIRTUALENVS=1
before_install:
  - pip install -U pip
  - pip install -U poetry
install:
  - poetry install
script:
  - python -m tox -s
after_success:
  - pipenv run codecov
jobs:
  include:
    - python: 3.8
    - python: 3.9
