language: python
before_install:
  - pip install -U pip
  - pip install -U -q codecov
  - pip install -U -q poetry
install:
  - poetry install
script:
  - poetry run python -m tox -s
after_success:
  - python -m codecov
jobs:
  include:
    - python: 3.8
    - python: 3.9
