language: python
before_install:
  - pip install -U pip
install:
  - pip install -U codecov
  - pip install -U tox
script:
  - python -m tox -s
after_success:
  - python -m codecov
jobs:
  include:
    - python: 3.8
    - python: 3.9
