name: Bibscrap Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update pip
      run: python -m pip install -U pip
    - name: Install tox
      run: python -m pip install -U tox
    - name: Install codecov
      run: python -m pip install -U codecov
    - name: Setup test suite
      run: python -m tox -vv --notest
    - name: Run test suite
      run: python -m tox
      env:
        PYTEST_ADDOPTS: "-vv --durations=20"
        CI_RUN: "yes"
        DIFF_AGAINST: HEAD
    - name: Upload coverage data
      run: python -m codecov
